# Generated by Django 4.0 on 2022-01-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('faculty', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('countage', models.PositiveSmallIntegerField(default=1)),
                ('classdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.class')),
            ],
            options={
                'unique_together': {('classdetails', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('EC', 'EC'), ('EE', 'EE'), ('EI', 'EI'), ('ET', 'ET'), ('ME', 'ME'), ('CV', 'CV'), ('BT', 'BT'), ('IM', 'IM'), ('AS', 'AS'), ('CH', 'CH')], max_length=5)),
                ('batch', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('dept_code', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='static/faces/')),
                ('json_encoding', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.section')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.currentsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.section'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('section', 'course_code')},
        ),
    ]
