# Generated by Django 4.0 on 2022-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_currentsession_is_active_present_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
