# Generated by Django 4.0 on 2022-01-20 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_present_timestamp_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsession',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
