# Generated by Django 4.0 on 2022-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_alter_present_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
